name: Create release

on:
  release:
    types:
      - created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Zip Folder
      run: zip -r "Multifogs_V${{github.ref_name}}.zip" . -i "Plugins/*"

    - name: Release
      uses: softprops/action-gh-release@v2
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: "Multifogs_V${{github.ref_name}}.zip"
        generate_release_notes: true
        make_latest: true
        token: ${{ secrets.RELEASE_TOKEN_PLUGINS }}
